// Command genplanners regenerates the Go planners of every variant listed in
// testdata/planners.txt (the manifest shared with the C++ oracle and the Nim
// port) into internal/generated/<variant>, plus the variant registry.
//
//	go run ./internal/tools/genplanners          # regenerate
//	go run ./internal/tools/genplanners -check   # fail when out of date
//
// It must run from the go/ module directory.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/primaryatias-oss/Slop-Port-Of-HTN-Planner-To-Go-And-Nim/go/htn/translator"
)

// Variant is one manifest entry.
type Variant struct {
	Name       string
	DomainPath string
	EntryPoint string
	Options    []string
}

func readManifest(path string) ([]Variant, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	var variants []Variant
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			return nil, fmt.Errorf("%s: malformed line %q", path, line)
		}
		variants = append(variants, Variant{Name: fields[0], DomainPath: fields[1], EntryPoint: fields[2], Options: fields[3:]})
	}
	return variants, scanner.Err()
}

func packageName(variant string) string { return strings.ToLower(variant) }

func main() {
	check := flag.Bool("check", false, "report out-of-date files instead of writing them")
	root := flag.String("root", "..", "repository root containing testdata/ and Domains/")
	out := flag.String("out", "internal/generated", "output directory")
	flag.Parse()

	variants, err := readManifest(filepath.Join(*root, "testdata", "planners.txt"))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	files := map[string][]byte{}
	for _, variant := range variants {
		request := translator.NewRequest(filepath.Join(*root, variant.DomainPath), variant.EntryPoint)
		for _, option := range variant.Options {
			if err := request.ApplyOption(option); err != nil {
				fmt.Fprintf(os.Stderr, "%s: option %s: %v\n", variant.Name, option, err)
				os.Exit(1)
			}
		}
		request.PackageName = packageName(variant.Name)
		result := translator.Generate(request)
		if !result.Succeeded {
			for _, d := range result.Diagnostics {
				fmt.Fprintf(os.Stderr, "%s(%d,%d): %s: %s\n", d.FilePath, d.Range.Begin.Line, d.Range.Begin.Column, d.Severity, d.Message)
			}
			fmt.Fprintf(os.Stderr, "%s: %s\n", variant.Name, result.ErrorMessage)
			os.Exit(1)
		}
		stem := strings.TrimSuffix(filepath.Base(variant.DomainPath), filepath.Ext(variant.DomainPath))
		files[filepath.Join(*out, packageName(variant.Name), stem+".generated.go")] = []byte(result.Source)
	}

	var registry bytes.Buffer
	registry.WriteString("// Code generated by genplanners. DO NOT EDIT.\n\n")
	registry.WriteString("// Package generated registers the Go planners generated from testdata/planners.txt.\n")
	registry.WriteString("package generated\n\nimport (\n")
	registry.WriteString("\t\"github.com/primaryatias-oss/Slop-Port-Of-HTN-Planner-To-Go-And-Nim/go/htn/planner\"\n")
	for _, variant := range variants {
		fmt.Fprintf(&registry, "\t\"github.com/primaryatias-oss/Slop-Port-Of-HTN-Planner-To-Go-And-Nim/go/internal/generated/%s\"\n", packageName(variant.Name))
	}
	registry.WriteString(")\n\n// Planners maps manifest variant names to generated definitions.\nvar Planners = map[string]func() *planner.Definition{\n")
	for _, variant := range variants {
		fmt.Fprintf(&registry, "\t%q: %s.%s_GetDefinition,\n", variant.Name, packageName(variant.Name), variant.EntryPoint)
	}
	registry.WriteString("}\n")
	formatted, err := format.Source(registry.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	files[filepath.Join(*out, "registry.go")] = formatted

	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	stale := 0
	for _, path := range paths {
		existing, readErr := os.ReadFile(path)
		if readErr == nil && bytes.Equal(existing, files[path]) {
			continue
		}
		if *check {
			fmt.Fprintf(os.Stderr, "out of date: %s\n", path)
			stale++
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, files[path], 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	if stale != 0 {
		fmt.Fprintf(os.Stderr, "%d generated file(s) are out of date; run go generate ./internal/generated\n", stale)
		os.Exit(1)
	}
}
