## Regenerates the Nim planners of every variant listed in
## testdata/planners.txt (shared with the C++ oracle and the Go port) into
## tests/generated/<variant>.nim, plus the variant registry.
##
##   nim r tools/genplanners.nim            # regenerate
##   nim r tools/genplanners.nim --check    # fail when out of date
##
## Run from the nim/ directory.

import std/[algorithm, os, strutils, tables]
import htn/translator

proc main() =
  var check = false
  var root = ".."
  var output = "tests/generated"
  for argument in commandLineParams():
    if argument == "--check": check = true
    elif argument.startsWith("--root="): root = argument["--root=".len .. ^1]
    elif argument.startsWith("--out="): output = argument["--out=".len .. ^1]
    else:
      stderr.writeLine "unknown argument: " & argument
      quit 1
  var files = initTable[string, string]()
  var registryImports, registryEntries: seq[string]
  for line in lines(root / "testdata" / "planners.txt"):
    let trimmed = line.strip()
    if trimmed.len == 0 or trimmed.startsWith("#"): continue
    let fields = trimmed.splitWhitespace()
    let (variant, domainPath, entryPoint) = (fields[0], fields[1], fields[2])
    var request = newRequest(root / domainPath, entryPoint)
    for option in fields[3 .. ^1]:
      let (status, message) = request.applyOption(option)
      if status != optionApplied:
        stderr.writeLine variant & ": option " & option & ": " & message
        quit 1
    let generated = generate(request)
    if not generated.succeeded:
      for d in generated.diagnostics:
        stderr.writeLine d.filePath & "(" & $d.range.first.line & "," & $d.range.first.column & "): " & d.message
      stderr.writeLine variant & ": " & generated.errorMessage
      quit 1
    let moduleName = variant.toLowerAscii()
    files[output / (moduleName & ".nim")] = generated.source
    registryImports.add moduleName
    registryEntries.add "  (" & escape(variant) & ", " & entryPoint & "_GetDefinition),"
  var registry = "# Code generated by genplanners. DO NOT EDIT.\n\n"
  registry.add "## Registers the Nim planners generated from testdata/planners.txt.\n\n"
  registry.add "import std/tables\nimport htn/planner\nimport\n"
  for i, name in registryImports:
    registry.add "  " & name & (if i + 1 < registryImports.len: ",\n" else: "\n")
  registry.add "\nlet planners*: Table[string, DefinitionGetter] = toTable[string, DefinitionGetter]([\n"
  registry.add registryEntries.join("\n") & "\n])\n"
  files[output / "registry.nim"] = registry
  var paths: seq[string]
  for path in files.keys: paths.add path
  paths.sort()
  var stale = 0
  for path in paths:
    let existing = if fileExists(path): readFile(path) else: ""
    if existing == files[path]: continue
    if check:
      stderr.writeLine "out of date: " & path
      inc stale
      continue
    createDir(parentDir(path))
    writeFile(path, files[path])
  if stale != 0:
    stderr.writeLine $stale & " generated file(s) are out of date; run nim r tools/genplanners.nim"
    quit 1

main()
