// Code generated by htn-translator. DO NOT EDIT.
// Source domain: Domains/Test/human.domain

package human

import (
	"math"

	"github.com/primaryatias-oss/Slop-Port-Of-HTN-Planner-To-Go-And-Nim/go/htn/atom"
	"github.com/primaryatias-oss/Slop-Port-Of-HTN-Planner-To-Go-And-Nim/go/htn/callterm"
	"github.com/primaryatias-oss/Slop-Port-Of-HTN-Planner-To-Go-And-Nim/go/htn/planner"
)

var _ = math.Float32frombits

var sym0 = atom.Intern("is_old")
var sym1 = atom.Intern("has_mold")
var sym2 = atom.Intern("item")
var sym3 = atom.Intern("edible")
var sym4 = atom.Intern("type")
var sym5 = atom.Intern("is_eating")
var sym6 = atom.Intern("is_wrapped")
var sym7 = atom.Intern("has_peel")
var sym8 = atom.Intern("!log")
var sym9 = atom.Intern("!talk")
var sym10 = atom.Intern("!take")
var sym11 = atom.Intern("!eat")
var sym12 = atom.Intern("!unwrap")
var sym13 = atom.Intern("!peel")
var sym14 = atom.Intern("behave")
var sym15 = atom.Intern("behave_upper_body")

var sv0 = atom.NewString("fruit")
var sv1 = atom.NewString("fruit")
var sv2 = atom.NewString("Error")
var sv3 = atom.NewString("This fruit is very tasty!")
var sv4 = atom.NewString("Error")
var sv5 = atom.NewString("we are doing nothing")
var sv6 = atom.NewString("fruit")
var sv7 = atom.NewString("Error")
var sv8 = atom.NewString("This fruit is very tasty!")
var sv9 = atom.NewString("Error")
var sv10 = atom.NewString("we are doing nothing")

var factSymbols = []*atom.Symbol{sym0, sym1, sym2, sym3, sym4, sym5, sym6, sym7}

var callNames = []string{"binded_function_with_args"}

var cs0 = callterm.Source{Domain: "Human", File: "Domains/Test/human.domain", Line: 99, Column: 9}
var cs1 = callterm.Source{Domain: "Human", File: "Domains/Test/human.domain", Line: 99, Column: 9}

var bc0 planner.BranchContinuations
var bc1 planner.BranchContinuations
var bc2 planner.BranchContinuations
var bc3 planner.BranchContinuations
var bc4 planner.BranchContinuations
var bc7 planner.BranchContinuations
var bc8 planner.BranchContinuations
var bc10 planner.BranchContinuations
var bc11 planner.BranchContinuations
var bc12 planner.BranchContinuations
var bc13 planner.BranchContinuations
var bc14 planner.BranchContinuations
var bc17 planner.BranchContinuations
var bc18 planner.BranchContinuations

var ms0 = []uint32{}
var ms1 = []uint32{3}
var ms2 = []uint32{3, 4}
var ms3 = []uint32{5}
var ms4 = []uint32{}
var ms5 = []uint32{3}
var ms6 = []uint32{3, 4}
var ms7 = []uint32{5}

func newExecution() *planner.Exec {
	return planner.NewExec(planner.Config{VariableCount: 6, FactCount: 8, CallTermCount: 1, CallFrameCapacity: 8192, FixedCapacity: false, BacktrackingCapacity: 32, SnapshotCapacity: 32, CapacityError: "Domains/Test/human.domain: Domain 'Human' exceeded its call-frame capacity (8192). Regenerate the domain with htn-translator --call-frame-capacity=<larger value> and recompile the generated code."})
}

type preparedData struct{ domain string }

var prepared = &preparedData{domain: "Human"}

var definition planner.Definition

// CreateHumanHTN_GetDefinition returns the generated planner definition of domain Human.
func CreateHumanHTN_GetDefinition() *planner.Definition { return &definition }

func init() {
	bc0 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task0}}, TotalRestore: 0}
	bc1 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task1}}, TotalRestore: 0}
	bc2 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task2}}, TotalRestore: 0}
	bc3 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task3}}, TotalRestore: 0}
	bc4 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task6, Restore: []uint32{5}}, {Fn: task5}, {Fn: task4}}, TotalRestore: 1}
	bc7 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task7}}, TotalRestore: 0}
	bc8 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task8}}, TotalRestore: 0}
	bc10 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task9}}, TotalRestore: 0}
	bc11 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task10}}, TotalRestore: 0}
	bc12 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task11}}, TotalRestore: 0}
	bc13 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task12}}, TotalRestore: 0}
	bc14 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task15, Restore: []uint32{5}}, {Fn: task14}, {Fn: task13}}, TotalRestore: 1}
	bc17 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task16}}, TotalRestore: 0}
	bc18 = planner.BranchContinuations{Tasks: []planner.PendingTask{{Fn: task17}}, TotalRestore: 0}
	definition = planner.Definition{
		ABIVersion:          planner.ABIVersion,
		Features:            planner.FeatureNone,
		DomainID:            "Human",
		SourceFile:          "Domains/Test/human.domain",
		NewPreparedStorage:  func() any { return prepared },
		NewExecutionStorage: newExecution,
		DecomposeCall:       decomposeCall,
		FactNames:           []string{"is_old", "has_mold", "item", "edible", "type", "is_eating", "is_wrapped", "has_peel"},
		CallTermRequirements: []callterm.Requirement{
			{Name: "binded_function_with_args", Source: callterm.Source{Domain: "Human", File: "Domains/Test/human.domain", Line: 99, Column: 9}},
		},
	}
	if planner.DebugEnabled {
		definition.DebugMetadata = newDebugMetadata()
	}
}

func newDebugMetadata() *planner.DebugMetadata {
	return planner.NewDebugMetadata(&planner.DebugTables{
		SourceFile: "Domains/Test/human.domain",
		Strings: []string{
			"unnamed",
			"fruit",
			"\"fruit\"",
			"Human::is_item_spoiled",
			"inp_item",
			"?inp_item",
			"is_old",
			"has_mold",
			"Human::find_edible_item",
			"inp_item_type",
			"?inp_item_type",
			"out_item",
			"?out_item",
			"item",
			"edible",
			"type",
			"is_item_spoiled",
			"find_edible_item",
			"Human::behave",
			"branch_hungry",
			"eat_food",
			"@fruit",
			"branch_fallback",
			"log",
			"!log",
			"Error",
			"\"Error\"",
			"Human::behave_upper_body",
			"branch_talk_about_food",
			"is_eating",
			"food",
			"?food",
			"talk",
			"!talk",
			"This fruit is very tasty!",
			"\"This fruit is very tasty!\"",
			"Human::eat_food",
			"inp_food_type",
			"?inp_food_type",
			"branch_food_in_possession",
			"take",
			"!take",
			"prepare_food",
			"eat",
			"!eat",
			"branch_get_food_from_house",
			"branch_buy_food_in_store",
			"Human::prepare_food",
			"inp_food",
			"?inp_food",
			"branch_unwrap_food",
			"is_wrapped",
			"unwrap",
			"!unwrap",
			"branch_peel_food",
			"has_peel",
			"peel",
			"!peel",
			"branch_do_nothing",
			"binded_function_with_args",
			"we are doing nothing",
			"\"we are doing nothing\"",
			"behave",
			"behave_upper_body",
		},
		Values: []uint32{
			2, 2, 1, 5, planner.NoIndex,
			1, 5, 4, 8, 0,
			1, 5, 4, 9, 0,
			1, 5, 4, 10, 0,
			1, 10, 9, 14, 1,
			1, 12, 11, 14, 2,
			1, 12, 11, 15, 2,
			1, 12, 11, 16, 2,
			1, 12, 11, 17, 2,
			1, 10, 9, 17, 1,
			1, 5, 4, 8, 0,
			1, 5, 4, 9, 0,
			1, 5, 4, 10, 0,
			1, 10, 9, 14, 1,
			1, 12, 11, 14, 2,
			1, 12, 11, 15, 2,
			1, 12, 11, 16, 2,
			1, 12, 11, 17, 2,
			1, 10, 9, 17, 1,
			2, 21, 1, 26, planner.NoIndex,
			2, 26, 25, 33, planner.NoIndex,
			1, 31, 30, 41, 3,
			2, 35, 34, 43, planner.NoIndex,
			2, 26, 25, 50, planner.NoIndex,
			1, 38, 37, 55, 4,
			1, 38, 37, 58, 4,
			1, 31, 30, 58, 3,
			1, 31, 30, 59, 3,
			1, 31, 30, 61, 3,
			1, 31, 30, 62, 3,
			1, 31, 30, 63, 3,
			1, 49, 48, 82, 5,
			1, 49, 48, 85, 5,
			1, 49, 48, 87, 5,
			1, 49, 48, 92, 5,
			1, 49, 48, 94, 5,
			2, 61, 60, 99, planner.NoIndex,
			2, 21, 1, 26, planner.NoIndex,
			2, 26, 25, 33, planner.NoIndex,
			1, 31, 30, 41, 3,
			2, 35, 34, 43, planner.NoIndex,
			2, 26, 25, 50, planner.NoIndex,
			1, 38, 37, 55, 4,
			1, 38, 37, 58, 4,
			1, 31, 30, 58, 3,
			1, 31, 30, 59, 3,
			1, 31, 30, 61, 3,
			1, 31, 30, 62, 3,
			1, 31, 30, 63, 3,
			1, 49, 48, 82, 5,
			1, 49, 48, 85, 5,
			1, 49, 48, 87, 5,
			1, 49, 48, 92, 5,
			1, 49, 48, 94, 5,
			2, 61, 60, 99, planner.NoIndex,
		},
		VariableStringIDs: []uint32{
			4,
			9,
			11,
			30,
			37,
			48,
		},
		Conditions: []uint32{
			3, planner.NoIndex, 0, 0, 0, 2, planner.NoIndex, planner.NoIndex, 9, 0,
			0, 6, 2, 1, 0, 0, planner.NoIndex, 0, 9, 0,
			0, 7, 3, 1, 0, 0, planner.NoIndex, 1, 10, 0,
			2, planner.NoIndex, 0, 0, 2, 3, planner.NoIndex, planner.NoIndex, 15, 0,
			0, 13, 6, 1, 2, 0, planner.NoIndex, 2, 15, 0,
			0, 14, 7, 1, 2, 0, planner.NoIndex, 3, 16, 0,
			0, 15, 8, 2, 2, 0, planner.NoIndex, 4, 17, 0,
			3, planner.NoIndex, 0, 0, 5, 2, planner.NoIndex, planner.NoIndex, 9, 0,
			0, 6, 11, 1, 5, 0, planner.NoIndex, 0, 9, 0,
			0, 7, 12, 1, 5, 0, planner.NoIndex, 1, 10, 0,
			2, planner.NoIndex, 0, 0, 7, 3, planner.NoIndex, planner.NoIndex, 15, 0,
			0, 13, 15, 1, 7, 0, planner.NoIndex, 2, 15, 0,
			0, 14, 16, 1, 7, 0, planner.NoIndex, 3, 16, 0,
			0, 15, 17, 2, 7, 0, planner.NoIndex, 4, 17, 0,
			2, planner.NoIndex, 0, 0, 10, 1, planner.NoIndex, planner.NoIndex, 41, 0,
			0, 29, 21, 1, 10, 0, planner.NoIndex, 5, 41, 0,
			2, planner.NoIndex, 0, 0, 12, 2, planner.NoIndex, planner.NoIndex, 58, 0,
			1, 17, 25, 2, 11, 0, planner.NoIndex, 3, 58, 0,
			5, planner.NoIndex, 0, 0, 11, 1, planner.NoIndex, planner.NoIndex, 59, 0,
			1, 16, 27, 1, 11, 0, planner.NoIndex, 2, 59, 0,
			2, planner.NoIndex, 0, 0, 14, 1, planner.NoIndex, planner.NoIndex, 85, 0,
			0, 51, 32, 1, 14, 0, planner.NoIndex, 6, 85, 0,
			2, planner.NoIndex, 0, 0, 15, 1, planner.NoIndex, planner.NoIndex, 92, 0,
			0, 55, 34, 1, 15, 0, planner.NoIndex, 7, 92, 0,
			2, planner.NoIndex, 0, 0, 16, 1, planner.NoIndex, planner.NoIndex, 99, 0,
			6, 59, 36, 1, 16, 0, planner.NoIndex, 0, 99, 0,
			2, planner.NoIndex, 0, 0, 17, 1, planner.NoIndex, planner.NoIndex, 41, 0,
			0, 29, 39, 1, 17, 0, planner.NoIndex, 5, 41, 0,
			2, planner.NoIndex, 0, 0, 19, 2, planner.NoIndex, planner.NoIndex, 58, 0,
			1, 17, 43, 2, 18, 0, planner.NoIndex, 3, 58, 0,
			5, planner.NoIndex, 0, 0, 18, 1, planner.NoIndex, planner.NoIndex, 59, 0,
			1, 16, 45, 1, 18, 0, planner.NoIndex, 2, 59, 0,
			2, planner.NoIndex, 0, 0, 21, 1, planner.NoIndex, planner.NoIndex, 85, 0,
			0, 51, 50, 1, 21, 0, planner.NoIndex, 6, 85, 0,
			2, planner.NoIndex, 0, 0, 22, 1, planner.NoIndex, planner.NoIndex, 92, 0,
			0, 55, 52, 1, 22, 0, planner.NoIndex, 7, 92, 0,
			2, planner.NoIndex, 0, 0, 23, 1, planner.NoIndex, planner.NoIndex, 99, 0,
			6, 59, 54, 1, 23, 0, planner.NoIndex, 0, 99, 0,
		},
		ConditionExpressions: []string{
			"(or ...)",
			"(is_old ?inp_item)",
			"(has_mold ?inp_item)",
			"(and ...)",
			"(item ?out_item)",
			"(edible ?out_item)",
			"(type ?out_item ?inp_item_type)",
			"(or ...)",
			"(is_old ?inp_item)",
			"(has_mold ?inp_item)",
			"(and ...)",
			"(item ?out_item)",
			"(edible ?out_item)",
			"(type ?out_item ?inp_item_type)",
			"(and ...)",
			"(is_eating ?food)",
			"(and ...)",
			"(#find_edible_item ?inp_food_type ?food)",
			"(not ...)",
			"(#is_item_spoiled ?food)",
			"(and ...)",
			"(is_wrapped ?inp_food)",
			"(and ...)",
			"(has_peel ?inp_food)",
			"(and ...)",
			"(call binded_function_with_args \"we are doing nothing\")",
			"(and ...)",
			"(is_eating ?food)",
			"(and ...)",
			"(#find_edible_item ?inp_food_type ?food)",
			"(not ...)",
			"(#is_item_spoiled ?food)",
			"(and ...)",
			"(is_wrapped ?inp_food)",
			"(and ...)",
			"(has_peel ?inp_food)",
			"(and ...)",
			"(call binded_function_with_args \"we are doing nothing\")",
		},
		ConditionChildRefs: []uint32{
			1,
			2,
			4,
			5,
			6,
			8,
			9,
			11,
			12,
			13,
			15,
			19,
			17,
			18,
			21,
			23,
			25,
			27,
			31,
			29,
			30,
			33,
			35,
			37,
		},
		Tasks: []uint32{
			0, 20, 19, 1, 26, planner.NoIndex,
			1, 23, 20, 1, 33, 24,
			1, 32, 22, 1, 43, 33,
			1, 23, 23, 1, 50, 24,
			1, 40, 28, 1, 61, 41,
			0, 42, 29, 1, 62, planner.NoIndex,
			1, 43, 30, 1, 63, 44,
			1, 52, 33, 1, 87, 53,
			1, 56, 35, 1, 94, 57,
			0, 20, 37, 1, 26, planner.NoIndex,
			1, 23, 38, 1, 33, 24,
			1, 32, 40, 1, 43, 33,
			1, 23, 41, 1, 50, 24,
			1, 40, 46, 1, 61, 41,
			0, 42, 47, 1, 62, planner.NoIndex,
			1, 43, 48, 1, 63, 44,
			1, 52, 51, 1, 87, 53,
			1, 56, 53, 1, 94, 57,
		},
		Branches: []uint32{
			19, planner.NoIndex, 0, 1, 23,
			22, planner.NoIndex, 1, 1, 30,
			28, 14, 2, 1, 40,
			22, planner.NoIndex, 3, 1, 47,
			39, 16, 4, 3, 57,
			45, planner.NoIndex, 7, 0, 67,
			46, planner.NoIndex, 7, 0, 74,
			50, 20, 7, 1, 84,
			54, 22, 8, 1, 91,
			58, 24, 9, 0, 98,
			19, planner.NoIndex, 9, 1, 23,
			22, planner.NoIndex, 10, 1, 30,
			28, 26, 11, 1, 40,
			22, planner.NoIndex, 12, 1, 47,
			39, 28, 13, 3, 57,
			45, planner.NoIndex, 16, 0, 67,
			46, planner.NoIndex, 16, 0, 74,
			50, 32, 16, 1, 84,
			54, 34, 17, 1, 91,
			58, 36, 18, 0, 98,
		},
		Methods: []uint64{
			18, 19, 0, 0, 2, 21, 0x0, 0x0, 0x0, 0x0,
			27, 21, 0, 2, 2, 38, 0x8, 0x0, 0x0, 0x0,
			36, 24, 1, 4, 3, 55, 0x18, 0x0, 0x0, 0x0,
			47, 31, 1, 7, 3, 82, 0x20, 0x0, 0x0, 0x0,
			62, 37, 0, 10, 2, 21, 0x0, 0x0, 0x0, 0x0,
			63, 39, 0, 12, 2, 38, 0x8, 0x0, 0x0, 0x0,
			20, 42, 1, 14, 3, 55, 0x18, 0x0, 0x0, 0x0,
			42, 49, 1, 17, 3, 82, 0x20, 0x0, 0x0, 0x0,
		},
		Axioms: []uint64{
			3, 1, 1, 0, 8, 0x1, 0x0, 0x0, 0x0,
			8, 4, 2, 3, 14, 0x6, 0x0, 0x0, 0x0,
			16, 10, 1, 7, 8, 0x1, 0x0, 0x0, 0x0,
			17, 13, 2, 10, 14, 0x6, 0x0, 0x0, 0x0,
		},
		Constants: []uint32{
			0, 1, 0, 5,
		},
		CallTermSlotCount: 1,
		FactSlotCount:     8,
		SourceFiles: []string{
			"Domains/Test/human.domain",
		},
		ValueSources: []uint32{
			0, 5, 16, 5, 23,
			0, 8, 30, 8, 39,
			0, 9, 25, 9, 34,
			0, 10, 27, 10, 36,
			0, 14, 31, 14, 45,
			0, 14, 46, 14, 55,
			0, 15, 23, 15, 32,
			0, 16, 25, 16, 34,
			0, 17, 23, 17, 32,
			0, 17, 33, 17, 47,
			0, 8, 30, 8, 39,
			0, 9, 25, 9, 34,
			0, 10, 27, 10, 36,
			0, 14, 31, 14, 45,
			0, 14, 46, 14, 55,
			0, 15, 23, 15, 32,
			0, 16, 25, 16, 34,
			0, 17, 23, 17, 32,
			0, 17, 33, 17, 47,
			0, 26, 31, 26, 37,
			0, 33, 27, 33, 34,
			0, 41, 32, 41, 37,
			0, 43, 28, 43, 55,
			0, 50, 27, 50, 34,
			0, 55, 24, 55, 38,
			0, 58, 40, 58, 54,
			0, 58, 55, 58, 60,
			0, 59, 44, 59, 49,
			0, 61, 28, 61, 33,
			0, 62, 35, 62, 40,
			0, 63, 27, 63, 32,
			0, 82, 28, 82, 37,
			0, 85, 33, 85, 42,
			0, 87, 30, 87, 39,
			0, 92, 31, 92, 40,
			0, 94, 28, 94, 37,
			0, 99, 41, 99, 63,
			0, 26, 31, 26, 37,
			0, 33, 27, 33, 34,
			0, 41, 32, 41, 37,
			0, 43, 28, 43, 55,
			0, 50, 27, 50, 34,
			0, 55, 24, 55, 38,
			0, 58, 40, 58, 54,
			0, 58, 55, 58, 60,
			0, 59, 44, 59, 49,
			0, 61, 28, 61, 33,
			0, 62, 35, 62, 40,
			0, 63, 27, 63, 32,
			0, 82, 28, 82, 37,
			0, 85, 33, 85, 42,
			0, 87, 30, 87, 39,
			0, 92, 31, 92, 40,
			0, 94, 28, 94, 37,
			0, 99, 41, 99, 63,
		},
		ConditionSources: []uint32{
			0, 9, 10, 10, 36,
			0, 9, 17, 9, 34,
			0, 10, 17, 10, 36,
			0, 15, 10, 17, 47,
			0, 15, 17, 15, 32,
			0, 16, 17, 16, 34,
			0, 17, 17, 17, 47,
			0, 9, 10, 10, 36,
			0, 9, 17, 9, 34,
			0, 10, 17, 10, 36,
			0, 15, 10, 17, 47,
			0, 15, 17, 15, 32,
			0, 16, 17, 16, 34,
			0, 17, 17, 17, 47,
			0, 41, 14, 41, 37,
			0, 41, 21, 41, 37,
			0, 58, 14, 59, 50,
			0, 58, 21, 58, 60,
			0, 59, 21, 59, 49,
			0, 59, 26, 59, 49,
			0, 85, 14, 85, 42,
			0, 85, 21, 85, 42,
			0, 92, 14, 92, 40,
			0, 92, 21, 92, 40,
			0, 99, 5, 99, 63,
			0, 99, 9, 99, 63,
			0, 41, 14, 41, 37,
			0, 41, 21, 41, 37,
			0, 58, 14, 59, 50,
			0, 58, 21, 58, 60,
			0, 59, 21, 59, 49,
			0, 59, 26, 59, 49,
			0, 85, 14, 85, 42,
			0, 85, 21, 85, 42,
			0, 92, 14, 92, 40,
			0, 92, 21, 92, 40,
			0, 99, 5, 99, 63,
			0, 99, 9, 99, 63,
		},
		TaskSources: []uint32{
			0, 26, 21, 26, 37,
			0, 33, 21, 33, 34,
			0, 43, 21, 43, 55,
			0, 50, 21, 50, 34,
			0, 61, 21, 61, 33,
			0, 62, 21, 62, 40,
			0, 63, 21, 63, 32,
			0, 87, 21, 87, 39,
			0, 94, 21, 94, 37,
			0, 26, 21, 26, 37,
			0, 33, 21, 33, 34,
			0, 43, 21, 43, 55,
			0, 50, 21, 50, 34,
			0, 61, 21, 61, 33,
			0, 62, 21, 62, 40,
			0, 63, 21, 63, 32,
			0, 87, 21, 87, 39,
			0, 94, 21, 94, 37,
		},
		BranchSources: []uint32{
			0, 23, 9, 28, 9,
			0, 30, 9, 35, 9,
			0, 40, 9, 45, 9,
			0, 47, 9, 52, 9,
			0, 57, 9, 65, 9,
			0, 67, 9, 72, 9,
			0, 74, 9, 79, 9,
			0, 84, 9, 89, 9,
			0, 91, 9, 96, 9,
			0, 98, 3, 103, 3,
			0, 23, 9, 28, 9,
			0, 30, 9, 35, 9,
			0, 40, 9, 45, 9,
			0, 47, 9, 52, 9,
			0, 57, 9, 65, 9,
			0, 67, 9, 72, 9,
			0, 74, 9, 79, 9,
			0, 84, 9, 89, 9,
			0, 91, 9, 96, 9,
			0, 98, 3, 103, 3,
		},
		MethodSources: []uint32{
			0, 21, 5, 36, 5,
			0, 38, 5, 53, 5,
			0, 55, 5, 80, 5,
			0, 82, 5, 105, 5,
			0, 21, 5, 36, 5,
			0, 38, 5, 53, 5,
			0, 55, 5, 80, 5,
			0, 82, 5, 105, 5,
		},
		AxiomSources: []uint32{
			0, 8, 5, 12, 5,
			0, 14, 5, 19, 5,
			0, 8, 5, 12, 5,
			0, 14, 5, 19, 5,
		},
		ConstantSources: []uint32{
			0, 5, 9, 5, 23,
		},
	})
}

func axiomBegin17(ex *planner.Exec, scope *planner.AxiomScope) {
	for i := range scope.Args {
		scope.Args[i] = atom.Atom{}
	}
	in0 := ex.V[4]
	in1 := ex.V[3]
	if in1.IsBound() {
		scope.Args[1] = in1
	}
	scope.Saved[0] = ex.V[1]
	ex.V[1] = atom.Atom{}
	scope.Saved[1] = ex.V[2]
	ex.V[2] = atom.Atom{}
	scope.CallerFrame = ex.CurrentFrameID
	ex.EnterFrame()
	if in0.IsBound() {
		ex.SetIfChanged(1, in0)
	}
	ex.DebugBeginAxiom(&definition, 3)
}

func axiomEnd17(ex *planner.Exec, succeeded bool, scope *planner.AxiomScope) bool {
	valid := succeeded
	if valid {
		if output := ex.V[2]; !output.IsBound() {
			valid = false
		} else if scope.Args[1].IsBound() && !atom.Equal(output, scope.Args[1]) {
			valid = false
		}
	}
	var out1 atom.Atom
	if valid {
		out1 = ex.V[2]
	}
	ex.DebugEndAxiom(&definition, valid)
	ex.V[1] = scope.Saved[0]
	ex.V[2] = scope.Saved[1]
	ex.CurrentFrameID = scope.CallerFrame
	if valid {
		ex.SetIfChanged(3, out1)
	}
	return valid
}

func axiomBegin19(ex *planner.Exec, scope *planner.AxiomScope) {
	for i := range scope.Args {
		scope.Args[i] = atom.Atom{}
	}
	in0 := ex.V[3]
	scope.Saved[0] = ex.V[0]
	ex.V[0] = atom.Atom{}
	scope.CallerFrame = ex.CurrentFrameID
	ex.EnterFrame()
	if in0.IsBound() {
		ex.SetIfChanged(0, in0)
	}
	ex.DebugBeginAxiom(&definition, 2)
}

func axiomEnd19(ex *planner.Exec, succeeded bool, scope *planner.AxiomScope) bool {
	valid := succeeded
	ex.DebugEndAxiom(&definition, valid)
	ex.V[0] = scope.Saved[0]
	ex.CurrentFrameID = scope.CallerFrame
	return valid
}

func axiomBegin29(ex *planner.Exec, scope *planner.AxiomScope) {
	for i := range scope.Args {
		scope.Args[i] = atom.Atom{}
	}
	in0 := ex.V[4]
	in1 := ex.V[3]
	if in1.IsBound() {
		scope.Args[1] = in1
	}
	scope.Saved[0] = ex.V[1]
	ex.V[1] = atom.Atom{}
	scope.Saved[1] = ex.V[2]
	ex.V[2] = atom.Atom{}
	scope.CallerFrame = ex.CurrentFrameID
	ex.EnterFrame()
	if in0.IsBound() {
		ex.SetIfChanged(1, in0)
	}
	ex.DebugBeginAxiom(&definition, 3)
}

func axiomEnd29(ex *planner.Exec, succeeded bool, scope *planner.AxiomScope) bool {
	valid := succeeded
	if valid {
		if output := ex.V[2]; !output.IsBound() {
			valid = false
		} else if scope.Args[1].IsBound() && !atom.Equal(output, scope.Args[1]) {
			valid = false
		}
	}
	var out1 atom.Atom
	if valid {
		out1 = ex.V[2]
	}
	ex.DebugEndAxiom(&definition, valid)
	ex.V[1] = scope.Saved[0]
	ex.V[2] = scope.Saved[1]
	ex.CurrentFrameID = scope.CallerFrame
	if valid {
		ex.SetIfChanged(3, out1)
	}
	return valid
}

func axiomBegin31(ex *planner.Exec, scope *planner.AxiomScope) {
	for i := range scope.Args {
		scope.Args[i] = atom.Atom{}
	}
	in0 := ex.V[3]
	scope.Saved[0] = ex.V[0]
	ex.V[0] = atom.Atom{}
	scope.CallerFrame = ex.CurrentFrameID
	ex.EnterFrame()
	if in0.IsBound() {
		ex.SetIfChanged(0, in0)
	}
	ex.DebugBeginAxiom(&definition, 2)
}

func axiomEnd31(ex *planner.Exec, succeeded bool, scope *planner.AxiomScope) bool {
	valid := succeeded
	ex.DebugEndAxiom(&definition, valid)
	ex.V[0] = scope.Saved[0]
	ex.CurrentFrameID = scope.CallerFrame
	return valid
}

func factChoice1(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[0][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[0]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[0].IsBound() && args[0].IsBound() {
			ex.V[0] = args[0]
		}
		return true
	}
	return false
}

func factChoice2(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[1][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[0]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[0].IsBound() && args[0].IsBound() {
			ex.V[0] = args[0]
		}
		return true
	}
	return false
}

func factChoice4(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[2][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[2]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[2].IsBound() && args[0].IsBound() {
			ex.V[2] = args[0]
		}
		return true
	}
	return false
}

func factChoice5(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[3][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[2]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[2].IsBound() && args[0].IsBound() {
			ex.V[2] = args[0]
		}
		return true
	}
	return false
}

func factChoice6(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[4][2]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[2]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if v := ex.V[1]; v.IsBound() && !atom.Equal(args[1], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[2].IsBound() && args[0].IsBound() {
			ex.V[2] = args[0]
		}
		if !ex.V[1].IsBound() && args[1].IsBound() {
			ex.V[1] = args[1]
		}
		return true
	}
	return false
}

func factChoice8(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[0][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[0]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[0].IsBound() && args[0].IsBound() {
			ex.V[0] = args[0]
		}
		return true
	}
	return false
}

func factChoice9(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[1][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[0]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[0].IsBound() && args[0].IsBound() {
			ex.V[0] = args[0]
		}
		return true
	}
	return false
}

func factChoice11(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[2][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[2]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[2].IsBound() && args[0].IsBound() {
			ex.V[2] = args[0]
		}
		return true
	}
	return false
}

func factChoice12(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[3][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[2]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[2].IsBound() && args[0].IsBound() {
			ex.V[2] = args[0]
		}
		return true
	}
	return false
}

func factChoice13(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[4][2]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[2]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if v := ex.V[1]; v.IsBound() && !atom.Equal(args[1], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[2].IsBound() && args[0].IsBound() {
			ex.V[2] = args[0]
		}
		if !ex.V[1].IsBound() && args[1].IsBound() {
			ex.V[1] = args[1]
		}
		return true
	}
	return false
}

func factChoice15(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[5][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[3]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[3].IsBound() && args[0].IsBound() {
			ex.V[3] = args[0]
		}
		return true
	}
	return false
}

func factChoice21(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[6][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[5]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[5].IsBound() && args[0].IsBound() {
			ex.V[5] = args[0]
		}
		return true
	}
	return false
}

func factChoice23(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[7][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[5]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[5].IsBound() && args[0].IsBound() {
			ex.V[5] = args[0]
		}
		return true
	}
	return false
}

func factChoice27(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[5][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[3]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[3].IsBound() && args[0].IsBound() {
			ex.V[3] = args[0]
		}
		return true
	}
	return false
}

func factChoice33(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[6][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[5]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[5].IsBound() && args[0].IsBound() {
			ex.V[5] = args[0]
		}
		return true
	}
	return false
}

func factChoice35(ex *planner.Exec, target uint32) bool {
	table := &ex.FactTables[7][1]
	var solution uint32
	for row, rows := 0, table.RowCount(); row < rows; row++ {
		args := table.Row(row)
		if v := ex.V[5]; v.IsBound() && !atom.Equal(args[0], v) {
			continue
		}
		if solution != target {
			solution++
			continue
		}
		if !ex.V[5].IsBound() && args[0].IsBound() {
			ex.V[5] = args[0]
		}
		return true
	}
	return false
}

func task0(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 0)
	// (eat_food @fruit)
	arg0 := sv1
	if !arg0.IsBound() {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.V[3] = atom.Atom{}
	ex.V[4] = atom.Atom{}
	ex.EnterFrame()
	ex.SetIfChanged(4, arg0)
	ex.Frame().Resume = 1
	ex.Next = method6
	return 2
}

func task1(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 1)
	// (!log "Error")
	if !ex.AppendPlanStep(sym8, []atom.Atom{sv2}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task2(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 2)
	// (!talk "This fruit is very tasty!")
	if !ex.AppendPlanStep(sym9, []atom.Atom{sv3}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task3(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 3)
	// (!log "Error")
	if !ex.AppendPlanStep(sym8, []atom.Atom{sv4}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task4(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 4)
	// (!take ?food)
	if !ex.AppendPlanStep(sym10, []atom.Atom{ex.V[3]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task5(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 5)
	// (prepare_food ?food)
	arg0 := ex.V[3]
	if !arg0.IsBound() {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.V[5] = atom.Atom{}
	ex.EnterFrame()
	ex.SetIfChanged(5, arg0)
	ex.Frame().Resume = 1
	ex.Next = method7
	return 2
}

func task6(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 6)
	// (!eat ?food)
	if !ex.AppendPlanStep(sym11, []atom.Atom{ex.V[3]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task7(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 7)
	// (!unwrap ?inp_food)
	if !ex.AppendPlanStep(sym12, []atom.Atom{ex.V[5]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task8(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 8)
	// (!peel ?inp_food)
	if !ex.AppendPlanStep(sym13, []atom.Atom{ex.V[5]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task9(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 9)
	// (eat_food @fruit)
	arg0 := sv6
	if !arg0.IsBound() {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.V[3] = atom.Atom{}
	ex.V[4] = atom.Atom{}
	ex.EnterFrame()
	ex.SetIfChanged(4, arg0)
	ex.Frame().Resume = 1
	ex.Next = method6
	return 2
}

func task10(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 10)
	// (!log "Error")
	if !ex.AppendPlanStep(sym8, []atom.Atom{sv7}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task11(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 11)
	// (!talk "This fruit is very tasty!")
	if !ex.AppendPlanStep(sym9, []atom.Atom{sv8}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task12(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 12)
	// (!log "Error")
	if !ex.AppendPlanStep(sym8, []atom.Atom{sv9}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task13(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 13)
	// (!take ?food)
	if !ex.AppendPlanStep(sym10, []atom.Atom{ex.V[3]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task14(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 14)
	// (prepare_food ?food)
	arg0 := ex.V[3]
	if !arg0.IsBound() {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.V[5] = atom.Atom{}
	ex.EnterFrame()
	ex.SetIfChanged(5, arg0)
	ex.Frame().Resume = 1
	ex.Next = method7
	return 2
}

func task15(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 15)
	// (!eat ?food)
	if !ex.AppendPlanStep(sym11, []atom.Atom{ex.V[3]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task16(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 16)
	// (!unwrap ?inp_food)
	if !ex.AppendPlanStep(sym12, []atom.Atom{ex.V[5]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

func task17(ex *planner.Exec) int {
	if frame := ex.Frame(); frame.Resume != 0 {
		ex.DebugEndTask(&definition, frame.ChildResult != 0)
		return frame.ChildResult
	}
	ex.DebugBeginTask(&definition, 17)
	// (!peel ?inp_food)
	if !ex.AppendPlanStep(sym13, []atom.Atom{ex.V[5]}) {
		ex.DebugEndTask(&definition, false)
		return 0
	}
	ex.DebugEndTask(&definition, true)
	return 1
}

// method0: Human::behave/0
func method0(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	switch frame.Resume {
	case 1:
		goto L4
	case 2:
		goto L5
	}
	ex.DebugBeginMethod(&definition, 0)
	goto L2
L2:
	// branch branch_hungry
	ex.SaveRetry(frame, ms0)
	ex.DebugBeginBranch(&definition, 0)
	goto L6
L6:
	if !ex.PushBranch(&bc0) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(0)
L8:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L4
	}
	goto L9
L4:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms0)
		ex.DebugEndBranch(&definition, false)
		goto L3
	}
	goto L8
L9:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L3:
	// branch branch_fallback
	ex.DebugBeginBranch(&definition, 1)
	goto L10
L10:
	if !ex.PushBranch(&bc1) {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(1)
L12:
	if ex.PendingCount() > 0 {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 2
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L5
	}
	goto L13
L5:
	if frame.ChildResult == 0 {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	goto L12
L13:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
}

// method1: Human::behave_upper_body/0
func method1(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	var cp22_3 atom.Atom
	var cp24_3 atom.Atom
	var fc25 uint32
	_ = cp22_3
	_ = cp24_3
	_ = fc25
	switch frame.Resume {
	case 1:
		goto L17
	case 2:
		goto L18
	}
	ex.DebugBeginMethod(&definition, 1)
	goto L15
L15:
	// branch branch_talk_about_food
	ex.SaveRetry(frame, ms1)
	ex.DebugBeginBranch(&definition, 2)
	// (and (is_eating ?food))
	cp22_3 = ex.V[3]
	ex.DebugBeginCondition(&definition, 14)
	// (is_eating ?food)
	cp24_3 = ex.V[3]
	fc25 = 0
	ex.DebugBeginCondition(&definition, 15)
	fc25++
	if !factChoice15(ex, fc25-1) {
		ex.DebugEndCondition(&definition, false)
		goto L23
	}
	ex.DebugEndCondition(&definition, true)
	ex.DebugEndCondition(&definition, true)
	goto L19
L23:
	ex.V[3] = cp24_3
	goto L21
L21:
	ex.V[3] = cp22_3
	ex.DebugEndCondition(&definition, false)
	goto L20
L20:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L16
L19:
	if !ex.PushBranch(&bc2) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(2)
L28:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L17
	}
	goto L29
L17:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms1)
		ex.DebugEndBranch(&definition, false)
		goto L16
	}
	goto L28
L29:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L16:
	// branch branch_fallback
	ex.DebugBeginBranch(&definition, 3)
	goto L30
L30:
	if !ex.PushBranch(&bc3) {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(3)
L32:
	if ex.PendingCount() > 0 {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 2
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L18
	}
	goto L33
L18:
	if frame.ChildResult == 0 {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	goto L32
L33:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
}

// method2: Human::eat_food/1
func method2(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	var cp42_3 atom.Atom
	var cp44_3 atom.Atom
	var as17_43Saved [2]atom.Atom
	var as17_43Args [2]atom.Atom
	var as17_43 planner.AxiomScope
	var as17_43Frame uint64
	var cp47_2 atom.Atom
	var cp49_2 atom.Atom
	var fc50 uint32
	var cp59_1 atom.Atom
	var cp59_2 atom.Atom
	var as17_43CopySaved [2]atom.Atom
	var as17_43CopyArgs [2]atom.Atom
	var as17_43Copy planner.AxiomScope
	var as19_65Saved [1]atom.Atom
	var as19_65Args [1]atom.Atom
	var as19_65 planner.AxiomScope
	var as19_65Frame uint64
	var cp75_0 atom.Atom
	var as19_65CopySaved [1]atom.Atom
	var as19_65CopyArgs [1]atom.Atom
	var as19_65Copy planner.AxiomScope
	var cp83_0 atom.Atom
	_ = cp42_3
	_ = cp44_3
	_ = as17_43Saved
	_ = as17_43Args
	_ = as17_43
	_ = as17_43Frame
	_ = cp47_2
	_ = cp49_2
	_ = fc50
	_ = cp59_1
	_ = cp59_2
	_ = as17_43CopySaved
	_ = as17_43CopyArgs
	_ = as17_43Copy
	_ = as19_65Saved
	_ = as19_65Args
	_ = as19_65
	_ = as19_65Frame
	_ = cp75_0
	_ = as19_65CopySaved
	_ = as19_65CopyArgs
	_ = as19_65Copy
	_ = cp83_0
	switch frame.Resume {
	case 1:
		goto L38
	}
	ex.DebugBeginMethod(&definition, 2)
	goto L35
L35:
	// branch branch_food_in_possession
	ex.SaveRetry(frame, ms2)
	ex.DebugBeginBranch(&definition, 4)
	// (and (#find_edible_item ?inp_food_type ?food) (not (#is_item_spoiled ?food)))
	cp42_3 = ex.V[3]
	ex.DebugBeginCondition(&definition, 16)
	// (#find_edible_item ?inp_food_type ?food)
	cp44_3 = ex.V[3]
	ex.DebugBeginCondition(&definition, 17)
	if ex.V[3].IsBound() {
		goto L43
	}
	as17_43 = planner.AxiomScope{Saved: as17_43Saved[:], Args: as17_43Args[:]}
	axiomBegin17(ex, &as17_43)
	as17_43Frame = ex.CurrentFrameID
	// (and (item ?out_item) (edible ?out_item) (type ?out_item ?inp_item_type))
	cp47_2 = ex.V[2]
	ex.DebugBeginCondition(&definition, 10)
	// (item ?out_item)
	cp49_2 = ex.V[2]
	fc50 = 0
L51:
	ex.DebugBeginCondition(&definition, 11)
	fc50++
	if !factChoice11(ex, fc50-1) {
		ex.DebugEndCondition(&definition, false)
		goto L48
	}
	ex.DebugEndCondition(&definition, true)
	// (edible ?out_item)
	// (edible ?out_item)
	{
		ex.DebugBeginCondition(&definition, 12)
		table := &ex.FactTables[3][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[2]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L54
		}
		goto L52
	}
L54:
	// (type ?out_item ?inp_item_type)
	// (type ?out_item ?inp_item_type)
	{
		ex.DebugBeginCondition(&definition, 13)
		table := &ex.FactTables[4][2]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[2]) {
				continue
			}
			if !atom.Equal(args[1], ex.V[1]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L57
		}
		goto L55
	}
L57:
	ex.DebugEndCondition(&definition, true)
	cp59_1 = ex.V[1]
	cp59_2 = ex.V[2]
	as17_43CopySaved = as17_43Saved
	as17_43CopyArgs = as17_43Args
	as17_43Copy = planner.AxiomScope{Saved: as17_43CopySaved[:], Args: as17_43CopyArgs[:], CallerFrame: as17_43.CallerFrame}
	if !axiomEnd17(ex, true, &as17_43Copy) {
		goto L60
	}
	ex.DebugEndCondition(&definition, true)
	// (not (#is_item_spoiled ?food))
	ex.DebugBeginCondition(&definition, 18)
	// (#is_item_spoiled ?food)
	ex.DebugBeginCondition(&definition, 19)
	as19_65 = planner.AxiomScope{Saved: as19_65Saved[:], Args: as19_65Args[:]}
	axiomBegin19(ex, &as19_65)
	as19_65Frame = ex.CurrentFrameID
	// (or (is_old ?inp_item) (has_mold ?inp_item))
	ex.DebugBeginCondition(&definition, 7)
	// (is_old ?inp_item)
	// (is_old ?inp_item)
	{
		ex.DebugBeginCondition(&definition, 8)
		table := &ex.FactTables[0][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[0]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L73
		}
		goto L71
	}
L73:
	ex.DebugEndCondition(&definition, true)
	cp75_0 = ex.V[0]
	as19_65CopySaved = as19_65Saved
	as19_65CopyArgs = as19_65Args
	as19_65Copy = planner.AxiomScope{Saved: as19_65CopySaved[:], Args: as19_65CopyArgs[:], CallerFrame: as19_65.CallerFrame}
	if !axiomEnd19(ex, true, &as19_65Copy) {
		goto L76
	}
	ex.DebugEndCondition(&definition, true)
	goto L62
L76:
	ex.V[0] = cp75_0
	ex.CurrentFrameID = as19_65Frame
	ex.DebugBeginAxiom(&definition, 2)
	goto L74
L74:
	ex.DebugBeginCondition(&definition, 7)
	goto L68
L71:
	goto L70
L70:
	// (has_mold ?inp_item)
	// (has_mold ?inp_item)
	{
		ex.DebugBeginCondition(&definition, 9)
		table := &ex.FactTables[1][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[0]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L81
		}
		goto L79
	}
L81:
	ex.DebugEndCondition(&definition, true)
	cp83_0 = ex.V[0]
	as19_65CopySaved = as19_65Saved
	as19_65CopyArgs = as19_65Args
	as19_65Copy = planner.AxiomScope{Saved: as19_65CopySaved[:], Args: as19_65CopyArgs[:], CallerFrame: as19_65.CallerFrame}
	if !axiomEnd19(ex, true, &as19_65Copy) {
		goto L84
	}
	ex.DebugEndCondition(&definition, true)
	goto L62
L84:
	ex.V[0] = cp83_0
	ex.CurrentFrameID = as19_65Frame
	ex.DebugBeginAxiom(&definition, 2)
	goto L82
L82:
	ex.DebugBeginCondition(&definition, 7)
	goto L68
L79:
	goto L78
L78:
	goto L68
L68:
	ex.DebugEndCondition(&definition, false)
	goto L67
L67:
	axiomEnd19(ex, false, &as19_65)
	goto L65
L65:
	ex.DebugEndCondition(&definition, false)
	goto L64
L64:
	ex.DebugEndCondition(&definition, true)
	ex.DebugEndCondition(&definition, true)
	goto L39
L62:
	ex.DebugEndCondition(&definition, false)
	goto L61
L61:
	ex.DebugBeginCondition(&definition, 17)
	goto L60
L60:
	ex.V[3] = cp44_3
	cp44_3 = ex.V[3]
	ex.V[1] = cp59_1
	ex.V[2] = cp59_2
	ex.CurrentFrameID = as17_43Frame
	ex.DebugBeginAxiom(&definition, 3)
	goto L58
L58:
	ex.DebugBeginCondition(&definition, 10)
	goto L55
L55:
	goto L52
L52:
	goto L50
L50:
	ex.V[2] = cp49_2
	cp49_2 = ex.V[2]
	goto L51
L48:
	ex.V[2] = cp49_2
	goto L46
L46:
	ex.V[2] = cp47_2
	ex.DebugEndCondition(&definition, false)
	goto L45
L45:
	axiomEnd17(ex, false, &as17_43)
	goto L43
L43:
	ex.V[3] = cp44_3
	ex.DebugEndCondition(&definition, false)
	goto L41
L41:
	ex.V[3] = cp42_3
	ex.DebugEndCondition(&definition, false)
	goto L40
L40:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L36
L39:
	if !ex.PushBranch(&bc4) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(6)
	ex.DebugCapturePendingTask(5)
	ex.DebugCapturePendingTask(4)
L88:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L38
	}
	goto L89
L38:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms2)
		ex.DebugEndBranch(&definition, false)
		goto L36
	}
	goto L88
L89:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L36:
	// branch branch_get_food_from_house
	ex.DebugBeginBranch(&definition, 5)
	goto L90
L90:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
}

// method3: Human::prepare_food/1
func method3(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	switch frame.Resume {
	case 1:
		goto L98
	case 2:
		goto L99
	}
	ex.DebugBeginMethod(&definition, 3)
	goto L95
L95:
	// branch branch_unwrap_food
	ex.SaveRetry(frame, ms3)
	ex.DebugBeginBranch(&definition, 7)
	// (and (is_wrapped ?inp_food))
	ex.DebugBeginCondition(&definition, 20)
	// (is_wrapped ?inp_food)
	// (is_wrapped ?inp_food)
	{
		ex.DebugBeginCondition(&definition, 21)
		table := &ex.FactTables[6][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[5]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L106
		}
		goto L104
	}
L106:
	ex.DebugEndCondition(&definition, true)
	goto L100
L104:
	goto L102
L102:
	ex.DebugEndCondition(&definition, false)
	goto L101
L101:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L96
L100:
	if !ex.PushBranch(&bc7) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(7)
L108:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L98
	}
	goto L109
L98:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms3)
		ex.DebugEndBranch(&definition, false)
		goto L96
	}
	goto L108
L109:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L96:
	// branch branch_peel_food
	ex.SaveRetry(frame, ms3)
	ex.DebugBeginBranch(&definition, 8)
	// (and (has_peel ?inp_food))
	ex.DebugBeginCondition(&definition, 22)
	// (has_peel ?inp_food)
	// (has_peel ?inp_food)
	{
		ex.DebugBeginCondition(&definition, 23)
		table := &ex.FactTables[7][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[5]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L116
		}
		goto L114
	}
L116:
	ex.DebugEndCondition(&definition, true)
	goto L110
L114:
	goto L112
L112:
	ex.DebugEndCondition(&definition, false)
	goto L111
L111:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L97
L110:
	if !ex.PushBranch(&bc8) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(8)
L118:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 2
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L99
	}
	goto L119
L99:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms3)
		ex.DebugEndBranch(&definition, false)
		goto L97
	}
	goto L118
L119:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L97:
	// branch branch_do_nothing
	ex.DebugBeginBranch(&definition, 9)
	// (and (call binded_function_with_args "we are doing nothing"))
	ex.DebugBeginCondition(&definition, 24)
	// (call binded_function_with_args "we are doing nothing")
	// (call binded_function_with_args "we are doing nothing")
	ex.DebugBeginCondition(&definition, 25)
	if result, ok := ex.Invoke(0, []atom.Atom{sv5}, &cs0, factSymbols); ok && result.Is(atom.KindBool) && result.Bool() {
		ex.DebugEndCondition(&definition, true)
		goto L126
	}
	ex.DebugEndCondition(&definition, false)
	goto L124
L126:
	ex.DebugEndCondition(&definition, true)
	goto L120
L124:
	goto L122
L122:
	ex.DebugEndCondition(&definition, false)
	goto L121
L121:
	ex.DebugEndBranch(&definition, false)
	goto L94
L120:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L94:
	ex.DebugEndMethod(&definition, false)
	return 0
}

// method4: behave/0
func method4(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	switch frame.Resume {
	case 1:
		goto L131
	case 2:
		goto L132
	}
	ex.DebugBeginMethod(&definition, 4)
	goto L129
L129:
	// branch branch_hungry
	ex.SaveRetry(frame, ms4)
	ex.DebugBeginBranch(&definition, 10)
	goto L133
L133:
	if !ex.PushBranch(&bc10) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(9)
L135:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L131
	}
	goto L136
L131:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms4)
		ex.DebugEndBranch(&definition, false)
		goto L130
	}
	goto L135
L136:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L130:
	// branch branch_fallback
	ex.DebugBeginBranch(&definition, 11)
	goto L137
L137:
	if !ex.PushBranch(&bc11) {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(10)
L139:
	if ex.PendingCount() > 0 {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 2
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L132
	}
	goto L140
L132:
	if frame.ChildResult == 0 {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	goto L139
L140:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
}

// method5: behave_upper_body/0
func method5(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	var cp149_3 atom.Atom
	var cp151_3 atom.Atom
	var fc152 uint32
	_ = cp149_3
	_ = cp151_3
	_ = fc152
	switch frame.Resume {
	case 1:
		goto L144
	case 2:
		goto L145
	}
	ex.DebugBeginMethod(&definition, 5)
	goto L142
L142:
	// branch branch_talk_about_food
	ex.SaveRetry(frame, ms5)
	ex.DebugBeginBranch(&definition, 12)
	// (and (is_eating ?food))
	cp149_3 = ex.V[3]
	ex.DebugBeginCondition(&definition, 26)
	// (is_eating ?food)
	cp151_3 = ex.V[3]
	fc152 = 0
	ex.DebugBeginCondition(&definition, 27)
	fc152++
	if !factChoice27(ex, fc152-1) {
		ex.DebugEndCondition(&definition, false)
		goto L150
	}
	ex.DebugEndCondition(&definition, true)
	ex.DebugEndCondition(&definition, true)
	goto L146
L150:
	ex.V[3] = cp151_3
	goto L148
L148:
	ex.V[3] = cp149_3
	ex.DebugEndCondition(&definition, false)
	goto L147
L147:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L143
L146:
	if !ex.PushBranch(&bc12) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(11)
L155:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L144
	}
	goto L156
L144:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms5)
		ex.DebugEndBranch(&definition, false)
		goto L143
	}
	goto L155
L156:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L143:
	// branch branch_fallback
	ex.DebugBeginBranch(&definition, 13)
	goto L157
L157:
	if !ex.PushBranch(&bc13) {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(12)
L159:
	if ex.PendingCount() > 0 {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 2
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L145
	}
	goto L160
L145:
	if frame.ChildResult == 0 {
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	goto L159
L160:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
}

// method6: eat_food/1
func method6(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	var cp169_3 atom.Atom
	var cp171_3 atom.Atom
	var as29_170Saved [2]atom.Atom
	var as29_170Args [2]atom.Atom
	var as29_170 planner.AxiomScope
	var as29_170Frame uint64
	var cp174_2 atom.Atom
	var cp176_2 atom.Atom
	var fc177 uint32
	var cp186_1 atom.Atom
	var cp186_2 atom.Atom
	var as29_170CopySaved [2]atom.Atom
	var as29_170CopyArgs [2]atom.Atom
	var as29_170Copy planner.AxiomScope
	var as31_192Saved [1]atom.Atom
	var as31_192Args [1]atom.Atom
	var as31_192 planner.AxiomScope
	var as31_192Frame uint64
	var cp202_0 atom.Atom
	var as31_192CopySaved [1]atom.Atom
	var as31_192CopyArgs [1]atom.Atom
	var as31_192Copy planner.AxiomScope
	var cp210_0 atom.Atom
	_ = cp169_3
	_ = cp171_3
	_ = as29_170Saved
	_ = as29_170Args
	_ = as29_170
	_ = as29_170Frame
	_ = cp174_2
	_ = cp176_2
	_ = fc177
	_ = cp186_1
	_ = cp186_2
	_ = as29_170CopySaved
	_ = as29_170CopyArgs
	_ = as29_170Copy
	_ = as31_192Saved
	_ = as31_192Args
	_ = as31_192
	_ = as31_192Frame
	_ = cp202_0
	_ = as31_192CopySaved
	_ = as31_192CopyArgs
	_ = as31_192Copy
	_ = cp210_0
	switch frame.Resume {
	case 1:
		goto L165
	}
	ex.DebugBeginMethod(&definition, 6)
	goto L162
L162:
	// branch branch_food_in_possession
	ex.SaveRetry(frame, ms6)
	ex.DebugBeginBranch(&definition, 14)
	// (and (#find_edible_item ?inp_food_type ?food) (not (#is_item_spoiled ?food)))
	cp169_3 = ex.V[3]
	ex.DebugBeginCondition(&definition, 28)
	// (#find_edible_item ?inp_food_type ?food)
	cp171_3 = ex.V[3]
	ex.DebugBeginCondition(&definition, 29)
	if ex.V[3].IsBound() {
		goto L170
	}
	as29_170 = planner.AxiomScope{Saved: as29_170Saved[:], Args: as29_170Args[:]}
	axiomBegin29(ex, &as29_170)
	as29_170Frame = ex.CurrentFrameID
	// (and (item ?out_item) (edible ?out_item) (type ?out_item ?inp_item_type))
	cp174_2 = ex.V[2]
	ex.DebugBeginCondition(&definition, 10)
	// (item ?out_item)
	cp176_2 = ex.V[2]
	fc177 = 0
L178:
	ex.DebugBeginCondition(&definition, 11)
	fc177++
	if !factChoice11(ex, fc177-1) {
		ex.DebugEndCondition(&definition, false)
		goto L175
	}
	ex.DebugEndCondition(&definition, true)
	// (edible ?out_item)
	// (edible ?out_item)
	{
		ex.DebugBeginCondition(&definition, 12)
		table := &ex.FactTables[3][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[2]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L181
		}
		goto L179
	}
L181:
	// (type ?out_item ?inp_item_type)
	// (type ?out_item ?inp_item_type)
	{
		ex.DebugBeginCondition(&definition, 13)
		table := &ex.FactTables[4][2]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[2]) {
				continue
			}
			if !atom.Equal(args[1], ex.V[1]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L184
		}
		goto L182
	}
L184:
	ex.DebugEndCondition(&definition, true)
	cp186_1 = ex.V[1]
	cp186_2 = ex.V[2]
	as29_170CopySaved = as29_170Saved
	as29_170CopyArgs = as29_170Args
	as29_170Copy = planner.AxiomScope{Saved: as29_170CopySaved[:], Args: as29_170CopyArgs[:], CallerFrame: as29_170.CallerFrame}
	if !axiomEnd29(ex, true, &as29_170Copy) {
		goto L187
	}
	ex.DebugEndCondition(&definition, true)
	// (not (#is_item_spoiled ?food))
	ex.DebugBeginCondition(&definition, 30)
	// (#is_item_spoiled ?food)
	ex.DebugBeginCondition(&definition, 31)
	as31_192 = planner.AxiomScope{Saved: as31_192Saved[:], Args: as31_192Args[:]}
	axiomBegin31(ex, &as31_192)
	as31_192Frame = ex.CurrentFrameID
	// (or (is_old ?inp_item) (has_mold ?inp_item))
	ex.DebugBeginCondition(&definition, 7)
	// (is_old ?inp_item)
	// (is_old ?inp_item)
	{
		ex.DebugBeginCondition(&definition, 8)
		table := &ex.FactTables[0][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[0]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L200
		}
		goto L198
	}
L200:
	ex.DebugEndCondition(&definition, true)
	cp202_0 = ex.V[0]
	as31_192CopySaved = as31_192Saved
	as31_192CopyArgs = as31_192Args
	as31_192Copy = planner.AxiomScope{Saved: as31_192CopySaved[:], Args: as31_192CopyArgs[:], CallerFrame: as31_192.CallerFrame}
	if !axiomEnd31(ex, true, &as31_192Copy) {
		goto L203
	}
	ex.DebugEndCondition(&definition, true)
	goto L189
L203:
	ex.V[0] = cp202_0
	ex.CurrentFrameID = as31_192Frame
	ex.DebugBeginAxiom(&definition, 2)
	goto L201
L201:
	ex.DebugBeginCondition(&definition, 7)
	goto L195
L198:
	goto L197
L197:
	// (has_mold ?inp_item)
	// (has_mold ?inp_item)
	{
		ex.DebugBeginCondition(&definition, 9)
		table := &ex.FactTables[1][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[0]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L208
		}
		goto L206
	}
L208:
	ex.DebugEndCondition(&definition, true)
	cp210_0 = ex.V[0]
	as31_192CopySaved = as31_192Saved
	as31_192CopyArgs = as31_192Args
	as31_192Copy = planner.AxiomScope{Saved: as31_192CopySaved[:], Args: as31_192CopyArgs[:], CallerFrame: as31_192.CallerFrame}
	if !axiomEnd31(ex, true, &as31_192Copy) {
		goto L211
	}
	ex.DebugEndCondition(&definition, true)
	goto L189
L211:
	ex.V[0] = cp210_0
	ex.CurrentFrameID = as31_192Frame
	ex.DebugBeginAxiom(&definition, 2)
	goto L209
L209:
	ex.DebugBeginCondition(&definition, 7)
	goto L195
L206:
	goto L205
L205:
	goto L195
L195:
	ex.DebugEndCondition(&definition, false)
	goto L194
L194:
	axiomEnd31(ex, false, &as31_192)
	goto L192
L192:
	ex.DebugEndCondition(&definition, false)
	goto L191
L191:
	ex.DebugEndCondition(&definition, true)
	ex.DebugEndCondition(&definition, true)
	goto L166
L189:
	ex.DebugEndCondition(&definition, false)
	goto L188
L188:
	ex.DebugBeginCondition(&definition, 29)
	goto L187
L187:
	ex.V[3] = cp171_3
	cp171_3 = ex.V[3]
	ex.V[1] = cp186_1
	ex.V[2] = cp186_2
	ex.CurrentFrameID = as29_170Frame
	ex.DebugBeginAxiom(&definition, 3)
	goto L185
L185:
	ex.DebugBeginCondition(&definition, 10)
	goto L182
L182:
	goto L179
L179:
	goto L177
L177:
	ex.V[2] = cp176_2
	cp176_2 = ex.V[2]
	goto L178
L175:
	ex.V[2] = cp176_2
	goto L173
L173:
	ex.V[2] = cp174_2
	ex.DebugEndCondition(&definition, false)
	goto L172
L172:
	axiomEnd29(ex, false, &as29_170)
	goto L170
L170:
	ex.V[3] = cp171_3
	ex.DebugEndCondition(&definition, false)
	goto L168
L168:
	ex.V[3] = cp169_3
	ex.DebugEndCondition(&definition, false)
	goto L167
L167:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L163
L166:
	if !ex.PushBranch(&bc14) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(15)
	ex.DebugCapturePendingTask(14)
	ex.DebugCapturePendingTask(13)
L215:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L165
	}
	goto L216
L165:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms6)
		ex.DebugEndBranch(&definition, false)
		goto L163
	}
	goto L215
L216:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L163:
	// branch branch_get_food_from_house
	ex.DebugBeginBranch(&definition, 15)
	goto L217
L217:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
}

// method7: prepare_food/1
func method7(ex *planner.Exec) int {
	frame := ex.Frame()
	_ = frame
	switch frame.Resume {
	case 1:
		goto L225
	case 2:
		goto L226
	}
	ex.DebugBeginMethod(&definition, 7)
	goto L222
L222:
	// branch branch_unwrap_food
	ex.SaveRetry(frame, ms7)
	ex.DebugBeginBranch(&definition, 17)
	// (and (is_wrapped ?inp_food))
	ex.DebugBeginCondition(&definition, 32)
	// (is_wrapped ?inp_food)
	// (is_wrapped ?inp_food)
	{
		ex.DebugBeginCondition(&definition, 33)
		table := &ex.FactTables[6][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[5]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L233
		}
		goto L231
	}
L233:
	ex.DebugEndCondition(&definition, true)
	goto L227
L231:
	goto L229
L229:
	ex.DebugEndCondition(&definition, false)
	goto L228
L228:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L223
L227:
	if !ex.PushBranch(&bc17) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(16)
L235:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 1
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L225
	}
	goto L236
L225:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms7)
		ex.DebugEndBranch(&definition, false)
		goto L223
	}
	goto L235
L236:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L223:
	// branch branch_peel_food
	ex.SaveRetry(frame, ms7)
	ex.DebugBeginBranch(&definition, 18)
	// (and (has_peel ?inp_food))
	ex.DebugBeginCondition(&definition, 34)
	// (has_peel ?inp_food)
	// (has_peel ?inp_food)
	{
		ex.DebugBeginCondition(&definition, 35)
		table := &ex.FactTables[7][1]
		matched := false
		for row, rows := 0, table.RowCount(); row < rows; row++ {
			args := table.Row(row)
			if !atom.Equal(args[0], ex.V[5]) {
				continue
			}
			matched = true
			break
		}
		ex.DebugEndCondition(&definition, matched)
		if matched {
			goto L243
		}
		goto L241
	}
L243:
	ex.DebugEndCondition(&definition, true)
	goto L237
L241:
	goto L239
L239:
	ex.DebugEndCondition(&definition, false)
	goto L238
L238:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, false)
	goto L224
L237:
	if !ex.PushBranch(&bc18) {
		ex.ReleaseRetry(frame)
		ex.DebugEndBranch(&definition, false)
		ex.DebugEndMethod(&definition, false)
		return 0
	}
	ex.DebugCapturePendingTask(17)
L245:
	if ex.PendingCount() > frame.RetryPendingBase {
		if next := ex.PopPending(); next != nil {
			frame.Resume = 2
			ex.Next = next
			return 2
		}
		frame.ChildResult = 0
		goto L226
	}
	goto L246
L226:
	if frame.ChildResult == 0 {
		if ex.FailureState != planner.NoPlan {
			ex.ReleaseRetry(frame)
			ex.DebugEndBranch(&definition, false)
			ex.DebugEndMethod(&definition, false)
			return 0
		}
		ex.RestoreRetry(frame, ms7)
		ex.DebugEndBranch(&definition, false)
		goto L224
	}
	goto L245
L246:
	ex.ReleaseRetry(frame)
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L224:
	// branch branch_do_nothing
	ex.DebugBeginBranch(&definition, 19)
	// (and (call binded_function_with_args "we are doing nothing"))
	ex.DebugBeginCondition(&definition, 36)
	// (call binded_function_with_args "we are doing nothing")
	// (call binded_function_with_args "we are doing nothing")
	ex.DebugBeginCondition(&definition, 37)
	if result, ok := ex.Invoke(0, []atom.Atom{sv10}, &cs1, factSymbols); ok && result.Is(atom.KindBool) && result.Bool() {
		ex.DebugEndCondition(&definition, true)
		goto L253
	}
	ex.DebugEndCondition(&definition, false)
	goto L251
L253:
	ex.DebugEndCondition(&definition, true)
	goto L247
L251:
	goto L249
L249:
	ex.DebugEndCondition(&definition, false)
	goto L248
L248:
	ex.DebugEndBranch(&definition, false)
	goto L221
L247:
	ex.DebugEndBranch(&definition, true)
	ex.DebugEndMethod(&definition, true)
	return 1
L221:
	ex.DebugEndMethod(&definition, false)
	return 0
}

func decomposeCall(ctx *planner.Context, call atom.Atom, requireTopLevel bool) (atom.Atom, planner.DecompositionStatus) {
	empty := atom.EmptyList()
	if ctx == nil || ctx.Execution == nil || ctx.Prepared == nil {
		return empty, planner.InvalidContext
	}
	ex := ctx.Execution
	ex.ResetDiagnostics()
	if ctx.WorldState == nil || ctx.Bindings == nil {
		return empty, planner.InvalidContext
	}
	if !call.Is(atom.KindList) || call.Len() < 1 {
		return empty, planner.InvalidCall
	}
	head, _ := call.At(0)
	if !head.Is(atom.KindSymbol) {
		return empty, planner.InvalidCall
	}
	argumentCount := call.Len() - 1
	_ = argumentCount
	ex.Begin(ctx, factSymbols, callNames)
	entry := -1
	if entry < 0 && head.Symbol() == sym14 && argumentCount == 0 {
		entry = 4
	}
	if entry < 0 && head.Symbol() == sym15 && argumentCount == 0 {
		entry = 5
	}
	if entry < 0 {
		return empty, planner.InvalidCall
	}
	ex.DebugBeginPlan(&definition, uint32(entry))
	result := 0
	switch entry {
	case 4:
		result = ex.Run(method4)
	case 5:
		result = ex.Run(method5)
	}
	if result == 0 {
		ex.DebugEndPlan(&definition, false)
		return empty, ex.FailureState
	}
	for ex.PendingCount() != 0 {
		next := ex.PopPending()
		if next == nil {
			break
		}
		if ex.Run(next) == 0 {
			ex.DebugEndPlan(&definition, false)
			return empty, ex.FailureState
		}
	}
	ex.DebugEndPlan(&definition, true)
	return ex.PlanAtom(), planner.Succeeded
}
